//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd_Pismire
{
    using System;
    using System.Collections.Generic;
    
    public partial class beneficios
    {
        public int idBeneficio { get; set; }
        public bool assistenciaSaude { get; set; }
        public bool assistenciaOdontologica { get; set; }
        public bool valeAlimentacao { get; set; }
        public bool valeCultura { get; set; }
        public bool trabalhoHomeOffice { get; set; }
        public bool valeViagem { get; set; }
        public bool salasDeConferencias { get; set; }
        public bool bolsasDeEstudos { get; set; }
        public int FK_evento { get; set; }
    
        public virtual evento evento { get; set; }
    }
}
