//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd_Pismire
{
    using System;
    using System.Collections.Generic;
    
    public partial class curriculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public curriculo()
        {
            this.avaliacao = new HashSet<avaliacao>();
            this.qualificacao_trabalhador = new HashSet<qualificacao_trabalhador>();
            this.trabalho_voluntario_trabalhador = new HashSet<trabalho_voluntario_trabalhador>();
            this.experiencia_internacional_trabalhador = new HashSet<experiencia_internacional_trabalhador>();
            this.experiencia_profissional_trabalhador = new HashSet<experiencia_profissional_trabalhador>();
            this.idioma_trabalhador = new HashSet<idioma_trabalhador>();
            this.interessados_empresa = new HashSet<interessados_empresa>();
            this.recomendados_empresa = new HashSet<recomendados_empresa>();
        }
    
        public int idCurriculo { get; set; }
        public string generoTrabalhador { get; set; }
        public string celularTrabalhador { get; set; }
        public string estadoCivil { get; set; }
        public string nacionalidade { get; set; }
        public bool deficienciaFisica { get; set; }
        public string estadoTrabalhador { get; set; }
        public string cidadeTrabalhador { get; set; }
        public string bairroTrabalhador { get; set; }
        public string ruaTrabalhador { get; set; }
        public string numeroTrabalhador { get; set; }
        public string cepTrabalhador { get; set; }
        public string areaAtuacao { get; set; }
        public string cargoAtuacao { get; set; }
        public string objetivo { get; set; }
        public string formacaoAcademica { get; set; }
        public bool situacaoAtual { get; set; }
        public string facebookTrabalhador { get; set; }
        public byte[] fotoUsuario { get; set; }
        public string FK_usuario_trabalhador { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<avaliacao> avaliacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qualificacao_trabalhador> qualificacao_trabalhador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trabalho_voluntario_trabalhador> trabalho_voluntario_trabalhador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<experiencia_internacional_trabalhador> experiencia_internacional_trabalhador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<experiencia_profissional_trabalhador> experiencia_profissional_trabalhador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<idioma_trabalhador> idioma_trabalhador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<interessados_empresa> interessados_empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recomendados_empresa> recomendados_empresa { get; set; }
        public virtual usuario_trabalhador usuario_trabalhador { get; set; }
    }
}
