//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd_Pismire
{
    using System;
    using System.Collections.Generic;
    
    public partial class evento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public evento()
        {
            this.beneficios = new HashSet<beneficios>();
            this.candidatos = new HashSet<candidatos>();
            this.experiencia_profissional_evento = new HashSet<experiencia_profissional_evento>();
            this.experiencia_internacional_evento = new HashSet<experiencia_internacional_evento>();
            this.interessados_trabalhador = new HashSet<interessados_trabalhador>();
            this.idioma_evento = new HashSet<idioma_evento>();
            this.qualificacao_evento = new HashSet<qualificacao_evento>();
        }
    
        public int idEvento { get; set; }
        public string vagaEvento { get; set; }
        public double salario { get; set; }
        public string turno { get; set; }
        public System.DateTime dataInicialEvento { get; set; }
        public System.DateTime dataFinalEvento { get; set; }
        public System.TimeSpan horarioInicialExpedienteEvento { get; set; }
        public System.TimeSpan horarioFinalExpedienteEvento { get; set; }
        public string areaEvento { get; set; }
        public string telefoneEvento { get; set; }
        public string tipoEmprego { get; set; }
        public string estadoEvento { get; set; }
        public string cidadeEvento { get; set; }
        public string bairroEvento { get; set; }
        public string ruaEvento { get; set; }
        public string numeroEvento { get; set; }
        public string cepEvento { get; set; }
        public string FK_usuario_empresa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<beneficios> beneficios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<candidatos> candidatos { get; set; }
        public virtual usuario_empresa usuario_empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<experiencia_profissional_evento> experiencia_profissional_evento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<experiencia_internacional_evento> experiencia_internacional_evento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<interessados_trabalhador> interessados_trabalhador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<idioma_evento> idioma_evento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qualificacao_evento> qualificacao_evento { get; set; }
    }
}
