//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd_Pismire
{
    using System;
    using System.Collections.Generic;
    
    public partial class experiencia_profissional_evento
    {
        public int idExperienciaEvento { get; set; }
        public string cargoExperienciaEvento { get; set; }
        public int FK_evento { get; set; }
    
        public virtual evento evento { get; set; }
    }
}
