//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd_Pismire
{
    using System;
    using System.Collections.Generic;
    
    public partial class idioma_evento
    {
        public int idIdiomaEvento { get; set; }
        public string linguaEvento { get; set; }
        public string nivelEvento { get; set; }
        public int FK_evento { get; set; }
    
        public virtual evento evento { get; set; }
    }
}
