//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd_Pismire
{
    using System;
    using System.Collections.Generic;
    
    public partial class mensagem
    {
        public int idMensagem { get; set; }
        public int destinatarioMensagem { get; set; }
        public string textoMensagem { get; set; }
        public System.DateTime dataMensagem { get; set; }
        public System.TimeSpan horarioMensagem { get; set; }
        public int FK_usuario { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
