//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd_Pismire
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PismireEntities2 : DbContext
    {
        public PismireEntities2()
            : base("name=PismireEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<avaliacao> avaliacao { get; set; }
        public virtual DbSet<beneficios> beneficios { get; set; }
        public virtual DbSet<candidatos> candidatos { get; set; }
        public virtual DbSet<curriculo> curriculo { get; set; }
        public virtual DbSet<evento> evento { get; set; }
        public virtual DbSet<experiencia_internacional_evento> experiencia_internacional_evento { get; set; }
        public virtual DbSet<experiencia_internacional_trabalhador> experiencia_internacional_trabalhador { get; set; }
        public virtual DbSet<experiencia_profissional_evento> experiencia_profissional_evento { get; set; }
        public virtual DbSet<experiencia_profissional_trabalhador> experiencia_profissional_trabalhador { get; set; }
        public virtual DbSet<idioma_evento> idioma_evento { get; set; }
        public virtual DbSet<idioma_trabalhador> idioma_trabalhador { get; set; }
        public virtual DbSet<interessados_empresa> interessados_empresa { get; set; }
        public virtual DbSet<interessados_trabalhador> interessados_trabalhador { get; set; }
        public virtual DbSet<mensagem> mensagem { get; set; }
        public virtual DbSet<notificacao> notificacao { get; set; }
        public virtual DbSet<perfil_empresa> perfil_empresa { get; set; }
        public virtual DbSet<preferencia> preferencia { get; set; }
        public virtual DbSet<qualificacao_evento> qualificacao_evento { get; set; }
        public virtual DbSet<qualificacao_trabalhador> qualificacao_trabalhador { get; set; }
        public virtual DbSet<recomendados_empresa> recomendados_empresa { get; set; }
        public virtual DbSet<recomendados_trabalhador> recomendados_trabalhador { get; set; }
        public virtual DbSet<trabalho_voluntario_trabalhador> trabalho_voluntario_trabalhador { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<usuario_empresa> usuario_empresa { get; set; }
        public virtual DbSet<usuario_trabalhador> usuario_trabalhador { get; set; }
    }
}
