//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd_Pismire
{
    using System;
    using System.Collections.Generic;
    
    public partial class notificacao
    {
        public int idNotificacao { get; set; }
        public string tituloNotificacao { get; set; }
        public string textoNotificacao { get; set; }
        public string dataNotificacao { get; set; }
        public string horarioNotificacao { get; set; }
        public bool situacaoNotificacao { get; set; }
        public int FK_usuario { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
