//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd_Pismire
{
    using System;
    using System.Collections.Generic;
    
    public partial class preferencia
    {
        public int idPreferencia { get; set; }
        public bool receberNotificacao { get; set; }
        public bool receberRecomendacoes { get; set; }
        public bool privacidade { get; set; }
        public bool localizacao { get; set; }
        public int FK_usuario { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
