//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd_Pismire
{
    using System;
    using System.Collections.Generic;
    
    public partial class qualificacao_trabalhador
    {
        public int idQualificacaoTrabalhador { get; set; }
        public string nomeQualificacaoTrabalhador { get; set; }
        public string tipoQualificacaoTrabalhador { get; set; }
        public string areaQualificacaoTrabalhador { get; set; }
        public string instituicaoQualificacaoTrabalhador { get; set; }
        public System.DateTime dataInicioQualificacaoTrabalhador { get; set; }
        public System.DateTime dataFinalQualificacaoTrabalhador { get; set; }
        public int FK_curriculo { get; set; }
    
        public virtual curriculo curriculo { get; set; }
    }
}
