//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd_Pismire
{
    using System;
    using System.Collections.Generic;
    
    public partial class trabalho_voluntario_trabalhador
    {
        public int idVoluntarioTrabalhador { get; set; }
        public string instituicaoVoluntarioTrabalhador { get; set; }
        public string responsavelVoluntarioTrabalhador { get; set; }
        public System.DateTime dataEntradaVoluntarioTrabalhador { get; set; }
        public System.DateTime dataSaidaVoluntarioTrabalhador { get; set; }
        public int FK_curriculo { get; set; }
    
        public virtual curriculo curriculo { get; set; }
    }
}
